sudo: false
language: node_js
node_js:
- 4
- 6
- 8
script:
  - npm test
after_success:
  - npm run report-cov
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    secure: AamPrY9gS1GgoVh5Qve+3MvDkPZ+HNg80vBEyr2YtC3l9rLZiEEpD7SdG/vxhurgYtgdozwCCfcg+q+tq0w+rcBZhjNGtk857zlZV8kFj/wMJgpVCVXY5K0eAq+84NSjz6najm5Jpo1fKWK42T4sJstzcbXhKXRy4vW2kfP89LqdBVU0rgJ5YaNLT9iFZQ6YLc0ThDOkVK14EJFTuMSY/tF6YPHziMUvVewTjvUcoBxaGaqVseqn4PwGqg6Egs4tI4ab18pwALDbnnTsnJJ5rkI2+689GAQddVR3mdnTrgVR0wdsuIGR/+uUUnIxsUPq1uxLBV/tVfSjhgEGY8+aXo6n1FsddJtU3JByMbnNmcjKXKdo41OCicuLCY3fLTODGSzrUSefwkWHt4GgaidctDzIVYkT5hWKON5rmoV4sz/X82e6ckb/OH6VscQC6GMv9epuCirDxZy8vRxn+d7Msy2ABwQ1jNtk4UX6obCFpaH7BVupM7pwHcRdA5C4V3C1SMdaN9kWVozTpH5HDCXO3ia6xh+OQr2+IIUGqBf4LIw3I26thoQWxAuLSk8WnjXRtwNPpTlCaaovO4+sDx2Z0PslAnG/OKErQgFTmMM9at90KSUzMnMYMG4RGrtOUHy6jUVzkmB9J3Oyhik/UB+seSii/LHga240RQY+EvJvzgQ=
  on:
    tags: true
    repo: Brightspace/node-auth-validation
